dist:     trusty
sudo:     required

language: cpp

os:
  - linux

before_install:
install: 
compiler:
  - g++
  - clang++ 

script:
  branches:
    only:
      - mambaru
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - echo Hello!!! 
