name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request (octokit/request-action@v2.x)
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: POST /repos/${{ github.repository }}/pulls
          title: "The title of the new pull request"
          head:  "mambaru"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
