name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: list_pull_requests
        with:
          route: GET /repos/${{ github.repository }}/pulls
          state: "open"
          head: "mambaru"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull request is exist
        if: contains(steps.list_pull_requests.outputs.data, 'id')==true
        run: |
          echo "Ну и ладно"

      - uses: octokit/request-action@v2.x
        id: create_pull_request
        if: contains(steps.list_pull_requests.outputs.data, 'id')==false
        with:
          route: POST /repos/${{ github.repository }}/pulls
          title: "The title of the new pull request"
          head: "mambaru"
          base: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
