name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Установка пакетов
        run: |
          sudo locale-gen ru_RU
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale
#          sudo apt-get install -y libboost-system-dev libboost-program-options-dev
#          sudo apt-get install -y libboost-filesystem-dev libboost-date-time-dev libboost-regex-dev
#          sudo apt-get install -y lcov

      - name: Генерация документации
        run: |
          make doc
        
      - name: Сборка
        run: |
          make coverage-report
          
      - name: Отчет о покрытии
        run: |
          echo pushd build
          echo   export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
          echo   bash <(curl -s https://codecov.io/bash)
          echo popd
        
      - name: Публикация документации
        run: |
          echo git clone -b gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git /tmp/gh-pages
          echo docdir="$PWD/docs/html/"
          echo pushd /tmp/gh-pages
          echo   git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          echo   git config --global user.name "${GITHUB_ACTOR}"
          echo   rsync -a --update $docdir ./
          echo   git add --all
          echo   COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          echo   git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
          echo   git commit -m "${COMMIT_MESSAGE}"
          echo   git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages:gh-pages
          echo popd

      - name: Плучение списка пул-реквестов mambaru
        uses: octokit/request-action@v2.x
        id: list_pull_requests
        with:
          route: GET /repos/${{ github.repository }}/pulls
          state: "open"
          head: "mambaru"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Пул-реквестов mambaru уже создан
        if: contains(steps.list_pull_requests.outputs.data, 'id')==true
        run: |
          echo "Ну и ладно"

      - name: Создаем Пул-реквест mambaru
        uses: octokit/request-action@v2.x
        id: create_pull_request
        if: contains(steps.list_pull_requests.outputs.data, 'id')==false
        with:
          route: POST /repos/${{ github.repository }}/pulls
          title: "The title of the new pull request"
          head: "mambaru"
          base: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
