name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: list_pull_requests
        with:
          route: GET /repos/${{ github.repository }}/pulls
          state: "open"
          head: "mambaru"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{steps.list_pull_requests.outputs.data[0]}}
          
      - name: Pull request is exist
        if: steps.list_pull_requests.outputs.data[0].id != 0
        run: |
          echo "Ну и ладно"

      - uses: octokit/request-action@v2.x
        id: create_pull_request
        if: steps.list_pull_requests.outputs.data[0].id == null
        continue-on-error: true
        with:
          route: POST /repos/${{ github.repository }}/pulls
          title: "The title of the new pull request"
          head: "mambaru"
          base: "master"
          maintainer_can_modify: true
          conclusion: "success"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Ну и ладно
        if: failure()
        run: |
          echo "Ну и ладно"
        
#      - run: "echo latest release: ${{ steps.create_pull_request.outputs.data }}"

