name: C++ CI

on:
  push:
    branches:
      - mambaru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: show
      run: |
        cat README.md
    - name: Create Pull Request (migashko)
      uses: migashko/create-pull-request@v1-test
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: mambaru
        branch-suffix: none
