name: C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale

        sudo apt-get install -y lcov
        echo "download boost"
        wget --quiet https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz
        echo "unzip boost"
        tar -xf boost_1_73_0.tar.gz
        push boost_1_73_0
          echo "bootstrap boost"
          ./bootstrap.sh
          echo "install boost"
          sudo ./b2 link=static runtime-link=static threading=multi install
          echo "boost Done!"
        popd
    - name: show
      run: |
        cat README.md
