name: C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo locale-gen ru_RU
        sudo locale-gen ru_RU.UTF-8
        sudo update-locale

        sudo apt-get install -y lcov
        ./boost-setup.sh
        echo $PATH
      working-directory: ./.github/workflows
    - name: show
      run: |
        cat README.md
